apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: checker
  name: checker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: checker
    spec:
      containers:
      - image: python
        name: checker
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: checker-claim0
      restartPolicy: Always
      volumes:
      - name: checker-claim0
        persistentVolumeClaim:
          claimName: checker-claim0
status: {}
